import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import dashboardRouter from "./dashboard.js";
import contactsRouter from "./contacts.js";
import dealsRouter from "./deals.js";
import adminRouter from "./admin.js";
import themeRouter from "./theme.js";
import messagesRouter from "./messages.js";
import filesRouter from "./files.js";
import analyticsRouter from "./analytics.js";
import templatesRouter from "./templates.js";
import paymentsRouter from "./payments.js";
import calendarRouter from "./calendar.js";
import artistsRouter from "./artists.js";
import searchRouter from "./search.js";
import onedriveRouter from "./onedrive.js";
import emailSettingsRouter from "./email-settings.js";
import integrationsRouter from "./integrations.js";
import formsRouter from "./forms.js";
import securityRouter from "./security.js";
import customFormsRouter from "./custom-forms.js";
import storageRouter from "./storage.js";
import deliverablesRouter from "./deliverables.js";
import portalRouter from "./portal.js";
import timeRouter from "./time.js";
import projectPagesRouter from "./project-pages.js";
import releasesRouter from "./releases.js";
import videoProjectsRouter from "./video-projects.js";
import projectsRouter from "./projects.js";
import releaseAssetsRouter from "./release-assets.js";
import royaltiesRouter from "./royalties.js";
import contentPostsRouter from "./content-posts.js";
import artistProfilesRouter from "./artist-profiles.js";
import artistSavedViewsRouter from "./artist-saved-views.js";
import automationsRouter from "./automations.js";
import mediaVersionsRouter from "./media-versions.js";
import subscriptionsRouter from "./subscriptions.js";
import invoicesRouter from "./invoices.js";
import notificationsRouter from "./notifications.js";
import dealTemplatesRouter from "./deal-templates.js";
import projectTemplatesRouter from "./project-templates.js";
import webhooksRouter from "./webhooks.js";
import apiKeysRouter from "./api-keys.js";
import microsoftAuthRouter from "./microsoft-auth.js";
import socialAuthRouter from "./social-auth.js";
import outlookRouter from "./outlook.js";
import invoiceEmailTemplatesRouter from "./invoice-email-templates.js";
import discoveryRouter from "./discovery.js";
import artistSweeperRouter from "./artist-sweeper.js";
import artistOutreachRouter from "./artist-outreach.js";
import artistDuplicatesRouter from "./artist-duplicates.js";
import artistRelationshipsRouter from "./artist-relationships.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/dashboard", dashboardRouter);
router.use("/contacts", contactsRouter);
router.use("/deals", dealsRouter);
router.use("/admin", adminRouter);
router.use("/theme", themeRouter);
router.use("/messages", messagesRouter);
router.use("/files", filesRouter);
router.use("/analytics", analyticsRouter);
router.use("/templates", templatesRouter);
router.use("/payments", paymentsRouter);
router.use("/calendar", calendarRouter);
router.use("/artists", artistDuplicatesRouter);
router.use("/artists", artistRelationshipsRouter);
router.use("/artists", artistsRouter);
router.use("/search", searchRouter);
router.use("/onedrive", onedriveRouter);
router.use("/email-settings", emailSettingsRouter);
router.use("/integrations", integrationsRouter);
router.use("/forms", formsRouter);
router.use("/security", securityRouter);
router.use("/custom-forms", customFormsRouter);
router.use(storageRouter);
// deliverables router owns its own full paths (/deals/:dealId/deliverables/*, /deliverables/*)
router.use(deliverablesRouter);
router.use("/portal", portalRouter);
router.use(timeRouter);
router.use("/pages", projectPagesRouter);
router.use("/releases", releasesRouter);
router.use("/video-projects", videoProjectsRouter);
router.use("/projects", projectsRouter);
router.use("/release-assets", releaseAssetsRouter);
router.use("/royalties", royaltiesRouter);
router.use("/content-posts", contentPostsRouter);
router.use("/artist-profiles", artistProfilesRouter);
router.use("/artist-saved-views", artistSavedViewsRouter);
router.use("/automations", automationsRouter);
router.use("/media-versions", mediaVersionsRouter);
router.use("/subscriptions", subscriptionsRouter);
router.use("/invoices", invoicesRouter);
router.use("/notifications", notificationsRouter);
router.use("/deal-templates", dealTemplatesRouter);
router.use("/project-templates", projectTemplatesRouter);
router.use("/webhooks", webhooksRouter);
router.use("/api-keys", apiKeysRouter);
router.use("/auth/microsoft", microsoftAuthRouter);
router.use("/auth/social", socialAuthRouter);
router.use("/outlook", outlookRouter);
router.use("/invoice-email-templates", invoiceEmailTemplatesRouter);
router.use("/discovery", discoveryRouter);
router.use("/artist-sweeper", artistSweeperRouter);
router.use("/artists", artistOutreachRouter);

export default router;
